=begin
#FireFawkes Developer API

#External Facing Developer API 

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for LogfaceClient::ApplicationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationsApi' do
  before do
    # run before each test
    @instance = LogfaceClient::ApplicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationsApi' do
    it 'should create an instance of ApplicationsApi' do
      expect(@instance).to be_instance_of(LogfaceClient::ApplicationsApi)
    end
  end

  # unit tests for application_get
  # Find applications
  # Find many applications
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :index Index of the first event in the set of returned results.  Negative index will count from the end of the results.
  # @option opts [Integer] :count Number of events desired.  Will return fewer if there are fewer to return.
  # @return [Array<ApplicationsResponse>]
  describe 'application_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for application_id_get
  # Find an application
  # Find an existing application
  # @param id id of the of the application
  # @param [Hash] opts the optional parameters
  # @return [Application]
  describe 'application_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
