=begin
#FireFawkes Developer API

#External Facing Developer API 

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for LogfaceClient::ContextApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContextApi' do
  before do
    # run before each test
    @instance = LogfaceClient::ContextApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContextApi' do
    it 'should create an instance of ContextApi' do
      expect(@instance).to be_instance_of(LogfaceClient::ContextApi)
    end
  end

  # unit tests for contexts_id_get
  # Retrieve context
  # This endpoint allows for retrieving events based on an SPL query. SPL Reference -- http://docs.splunk.com/Documentation/Splunk/latest/SearchReference/WhatsInThisManual 
  # @param id 
  # @param tenant_id ID of the tenant
  # @param [Hash] opts the optional parameters
  # @return [SearchContext]
  describe 'contexts_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for contexts_post
  # Create a search context
  # 
  # @param search_context 
  # @param tenant_id ID of the tenant
  # @param [Hash] opts the optional parameters
  # @return [SearchContext]
  describe 'contexts_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
