=begin
#FireFawkes Developer API

#External Facing Developer API 

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for LogfaceClient::IdentityApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'IdentityApi' do
  before do
    # run before each test
    @instance = LogfaceClient::IdentityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IdentityApi' do
    it 'should create an instance of IdentityApi' do
      expect(@instance).to be_instance_of(LogfaceClient::IdentityApi)
    end
  end

  # unit tests for account_api_keys_client_id_delete
  # Delete API Key
  # Delete the API Key
  # @param client_id the client ID of the API Key to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'account_api_keys_client_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_api_keys_client_id_get
  # Get API Key
  # Retrieve the api key for the current account, specified by ID
  # @param client_id the client ID to retrieve
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyResponse]
  describe 'account_api_keys_client_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_api_keys_client_id_put
  # Update the API Key
  # Enable/Disable the API Key
  # @param client_id the client ID of the API to update
  # @param [Hash] opts the optional parameters
  # @option opts [Body2] :body 
  # @return [ApiKeyResponse]
  describe 'account_api_keys_client_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_api_keys_get
  # Get API Keys
  # Retrieve the api keys for the current account
  # @param [Hash] opts the optional parameters
  # @return [ApiKeysResponse]
  describe 'account_api_keys_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_api_keys_post
  # New API Key
  # Create a new API Key
  # @param [Hash] opts the optional parameters
  # @option opts [Body1] :body 
  # @return [ApiKeyResponse]
  describe 'account_api_keys_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_get
  # Accounts represent individuals
  # Retrieve an account
  # @param [Hash] opts the optional parameters
  # @return [AccountResponse]
  describe 'account_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_put
  # Set whether the TOS has been agreed to
  # Update the TOS boolean for an account
  # @param [Hash] opts the optional parameters
  # @option opts [Body] :body 
  # @return [AccountResponse]
  describe 'account_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tenants_get
  # Get tenants
  # Get all tenants for a user
  # @param [Hash] opts the optional parameters
  # @return [Array<Tenant>]
  describe 'tenants_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tenants_post
  # Add a tenant
  # Add a new tenant and assign to the user
  # @param [Hash] opts the optional parameters
  # @option opts [Body6] :body 
  # @return [Tenant]
  describe 'tenants_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
