=begin
#FireFawkes Developer API

#External Facing Developer API 

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for LogfaceClient::LoginApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LoginApi' do
  before do
    # run before each test
    @instance = LogfaceClient::LoginApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoginApi' do
    it 'should create an instance of LoginApi' do
      expect(@instance).to be_instance_of(LogfaceClient::LoginApi)
    end
  end

  # unit tests for login_authorize_callback_get
  # Endpoint call via a social login oauth2 callback
  # Callback for OAuth2 Social logins
  # @param state 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :code 
  # @option opts [String] :token 
  # @return [Error]
  describe 'login_authorize_callback_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login_authorize_get
  # Endpoint to begin the oauth2 authorization flow
  # Does the initial social auth redirect
  # @param provider 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :redirect_url 
  # @return [Error]
  describe 'login_authorize_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login_oauth_revoke_post
  # Revoke a refresh token
  # Revoke a refresh token
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'login_oauth_revoke_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login_oauth_token_post
  # Get JWT for API Keys
  # Issue a token for an api key
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Token]
  describe 'login_oauth_token_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login_providers_get
  # Returns a list of social providers
  # Retrieve social providers
  # @param [Hash] opts the optional parameters
  # @return [Array<SocialProvider>]
  describe 'login_providers_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login_token_post
  # Endpoint to get a new refresh token
  # Gets the token for a given refresh token
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Token]
  describe 'login_token_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
