=begin
#FireFawkes Developer API

#External Facing Developer API 

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LogfaceClient::ApiKeyResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiKeyResponse' do
  before do
    # run before each test
    @instance = LogfaceClient::ApiKeyResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiKeyResponse' do
    it 'should create an instance of ApiKeyResponse' do
      expect(@instance).to be_instance_of(LogfaceClient::ApiKeyResponse)
    end
  end
end

