=begin
#FireFawkes Developer API

#External Facing Developer API 

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LogfaceClient::EventsReturn
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EventsReturn' do
  before do
    # run before each test
    @instance = LogfaceClient::EventsReturn.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsReturn' do
    it 'should create an instance of EventsReturn' do
      expect(@instance).to be_instance_of(LogfaceClient::EventsReturn)
    end
  end
  describe 'test attribute "bytes"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "count"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

